- name: private server hello world
  hosts: 127.0.0.1
  become: true
  tasks:
    - name: install nginx
      yum:
        name: nginx
        state: present

    - name: configure nginx for private subnet
      template:
        src: private-nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: restart nginx
      service:
        name: nginx
        state: restarted

