- name: public proxy servers
  hosts: 127.0.0.1
  become: true
  tasks:
    - name: install  nginx
      yum:
        name: nginx
        state: present

    - name: remove default nginx configuration
      file:
        name: /etc/nginx/sites-enabled/default
        state: absent

    - name: configure nginx for public subnet
      template:
        src: public-nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: start nginx
      service:
        name: nginx
        state: started